workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      # android_signing:
      #   - keystore_reference
      # Uncomment above and add keystore in Codemagic dashboard (Code signing identities)
      # to enable signed release builds
      groups:
        - google_play
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd flutter_note_app
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd flutter_note_app
          flutter analyze --no-fatal-infos
      - name: Build APK with Flutter
        script: |
          cd flutter_note_app
          flutter build apk --release
    artifacts:
      - flutter_note_app/build/**/outputs/**/*.apk
      - flutter_note_app/build/**/outputs/**/mapping.txt
      - flutter_note_app/flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.flutterNoteApp
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          cd flutter_note_app/ios
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd flutter_note_app
          flutter packages pub get
      - name: Install pods
        script: |
          cd flutter_note_app/ios
          pod install
      - name: Flutter build ipa
        script: |
          cd flutter_note_app
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - flutter_note_app/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_note_app/flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false
